### ISSUE TITLE
add progress tracker page

### ISSUE THREAD

**Issue by gregcaporaso** [applied-bioinformatics/An-Introduction-To-Applied-Bioinformatics#97]
The following are goals for IAB by March 31, 2018, which were developed in discussion with the [Sloan Foundation](www.sloan.org), the primary funding source for the project as of this writing. A single webpage that consolidates this information should be created and linked from the main page. _Italicized_ text is quoted from emails with Sloan. This issue is intended to track the creation of pages for each of these (not completion of each goal). 
- [ ] _20 GitHub contributors with more than one commit by project completion._ This will pull from the GitHub contributors page.
- [ ] _Used to teach at 10 bioinformatics workshops within one year of project completion. This number is based roughly on the number of QIIME workshops currently taught per year. I expect that there will be a similar amount of interest as this project gains popularity, and some of the content produced here will be taught at QIIME workshops._ This will be a new page that we'll create as a markdown table. 
- [ ] _Used to teach one or more university courses at 20 different universities within one year of project completion. This number is based on 10 reviewers using it in one class, and recommending to one other colleague each._ This will be a new page that we'll create as a markdown table.
- [ ] _7200 unique users within one year of completion. In the peak month so far I've had 300 unique visitors, so this number is determined by achieving that level every month in the year following completion, and half that per month in the two years leading to completion._ This will pull from Google Analytics. 

Additionally, the website will contain:
- [ ] public project timeline (which will derive from the milestones/issues as described in #89)
- [ ] When all of the above are complete, update the _Reading IAB_ chapter (#101) to point to the main entry point to that page.
